baseurl = "https://emmapierron.github.io/Repertoire-de-litterature-sapphique/"
#relativeURLs = true
title = "Litt√©rature saphique"
theme = "book"


[params]
  BookMenuBundle = "/menu"
  BookTheme = "light"

[outputFormats]
  [outputFormats.print]
    mediaType = "text/html" # normal
    rel = "print" # rapport
    baseName = "print" # /print dans l'URL

[permalinks]
  pages = "/:filename"
  blog = "/blog/:title"

[markup]
  [markup.goldmark]
    typographer = true
    [markup.goldmark.renderer]
     footnoteReturnLinkContents = "&uarr;"
      unsafe = true

copyright = "Date Auteur Licence"
languageCode = "en-us"

[author]
